#define				VOID			1
#define				VAR				2
#define				CONST			3
#define 			IF				4
#define				ELSE			5
#define				WHILE			6
#define				PRINT			7
#define				READ			8
#define				ID		 		9
#define				INTLITERAL		10
#define				STRING			11
#define				LPAREN			12
#define				RPAREN			13
#define				SEMICOLON		14
#define				COMMA			15
#define				ASSIGNOP		16
#define				PLUSOP			17
#define				MINUSOP			18
#define				MULTOP			19
#define				DIVOP			20
#define				BKL				21
#define				BKR				22
